[tools]
bat = "latest"
chezmoi = "latest"
fzf = "latest"
lsd = "latest"
fd = "latest"
lazygit = "latest"
node = "latest"
ripgrep = "latest"
neovim = "latest"
direnv = "latest"
yq = "latest"
kubeconform = "latest"
gemini-cli = "latest"
