[tools]
bat = "latest"
chezmoi = "latest"
fzf = "latest"
lsd = "latest"
fd = "latest"
lazygit = "latest"
node = "latest"
ripgrep = "latest"
neovim = "latest"
kubectl = "latest"
kubectx = "latest"
kubens = "latest"
k9s = "latest"
direnv = "latest"
flux2 = "latest"
sops = "latest"
age = "latest"
yq = "latest"
kubeconform = "latest"
krew = "latest"
claude-code = "2.0.55"
gemini-cli = "0.19.3"
